/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class TAppartenirASchema extends BaseModel {
  static $columns = ['createdAt', 'paysId', 'siteId', 'updatedAt'] as const
  $columns = TAppartenirASchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare paysId: number
  @column({ isPrimary: true })
  declare siteId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TPaySchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'nom', 'updatedAt'] as const
  $columns = TPaySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nom: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TRegionSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'label', 'updatedAt'] as const
  $columns = TRegionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare label: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TSiteSchema extends BaseModel {
  static $columns = ['categorie', 'createdAt', 'id', 'latitude', 'lienImage', 'longitude', 'regionId', 'updatedAt'] as const
  $columns = TSiteSchema.$columns
  @column()
  declare categorie: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare latitude: number
  @column()
  declare lienImage: string | null
  @column()
  declare longitude: number
  @column()
  declare regionId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TSiteTraductionSchema extends BaseModel {
  static $columns = ['codeLangue', 'createdAt', 'description', 'id', 'imageAlt', 'nom', 'siteId', 'updatedAt'] as const
  $columns = TSiteTraductionSchema.$columns
  @column()
  declare codeLangue: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare imageAlt: string | null
  @column()
  declare nom: string
  @column()
  declare siteId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TUserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'id', 'motDePasse', 'nom', 'updatedAt'] as const
  $columns = TUserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare motDePasse: string
  @column()
  declare nom: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TUserSiteAVisiterSchema extends BaseModel {
  static $columns = ['couleur', 'createdAt', 'siteId', 'updatedAt', 'userId'] as const
  $columns = TUserSiteAVisiterSchema.$columns
  @column()
  declare couleur: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare siteId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column({ isPrimary: true })
  declare userId: number
}

export class TUserSiteDejaVisiteSchema extends BaseModel {
  static $columns = ['createdAt', 'siteId', 'updatedAt', 'userId'] as const
  $columns = TUserSiteDejaVisiteSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare siteId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column({ isPrimary: true })
  declare userId: number
}
