import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Pays from '#models/pays'

export default class extends BaseSeeder {
  async run() {
    await Pays.createMany([
      { id: 1, nom: 'Afghanistan' },
      { id: 2, nom: 'Albania' },
      { id: 3, nom: 'Algeria' },
      { id: 4, nom: 'Andorra' },
      { id: 5, nom: 'Angola' },
      { id: 6, nom: 'Antigua and Barbuda' },
      { id: 7, nom: 'Argentina' },
      { id: 8, nom: 'Armenia' },
      { id: 9, nom: 'Australia' },
      { id: 10, nom: 'Austria' },
      { id: 11, nom: 'Azerbaijan' },
      { id: 12, nom: 'Bahrain' },
      { id: 13, nom: 'Bangladesh' },
      { id: 14, nom: 'Belarus' },
      { id: 15, nom: 'Belgium' },
      { id: 16, nom: 'Belize' },
      { id: 17, nom: 'Benin' },
      { id: 18, nom: 'Bhutan' },
      { id: 19, nom: 'Bolivia (Plurinational State of)' },
      { id: 20, nom: 'Bosnia and Herzegovina' },
      { id: 21, nom: 'Botswana' },
      { id: 22, nom: 'Brazil' },
      { id: 23, nom: 'Bulgaria' },
      { id: 24, nom: 'Burkina Faso' },
      { id: 25, nom: 'Cabo Verde' },
      { id: 26, nom: 'Cambodia' },
      { id: 27, nom: 'Cameroon' },
      { id: 28, nom: 'Canada' },
      { id: 29, nom: 'Central African Republic' },
      { id: 30, nom: 'Chad' },
      { id: 31, nom: 'Chile' },
      { id: 32, nom: 'China' },
      { id: 33, nom: 'Colombia' },
      { id: 34, nom: 'Congo' },
      { id: 35, nom: "Côte d'Ivoire" },
      { id: 36, nom: 'Croatia' },
      { id: 37, nom: 'Cuba' },
      { id: 38, nom: 'Cyprus' },
      { id: 39, nom: 'Czechia' },
      { id: 40, nom: "Democratic People's Republic of Korea" },
      { id: 41, nom: 'Democratic Republic of the Congo' },
      { id: 42, nom: 'Denmark' },
      { id: 43, nom: 'Dominica' },
      { id: 44, nom: 'Dominican Republic' },
      { id: 45, nom: 'Ecuador' },
      { id: 46, nom: 'Egypt' },
      { id: 47, nom: 'El Salvador' },
      { id: 48, nom: 'Eritrea' },
      { id: 49, nom: 'Estonia' },
      { id: 50, nom: 'Ethiopia' },
      { id: 51, nom: 'Fiji' },
      { id: 52, nom: 'Finland' },
      { id: 53, nom: 'France' },
      { id: 54, nom: 'Gabon' },
      { id: 55, nom: 'Gambia (the)' },
      { id: 56, nom: 'Georgia' },
      { id: 57, nom: 'Germany' },
      { id: 58, nom: 'Ghana' },
      { id: 59, nom: 'Greece' },
      { id: 60, nom: 'Guatemala' },
      { id: 61, nom: 'Haiti' },
      { id: 62, nom: 'Honduras' },
      { id: 63, nom: 'Hungary' },
      { id: 64, nom: 'Iceland' },
      { id: 65, nom: 'India' },
      { id: 66, nom: 'Indonesia' },
      { id: 67, nom: 'Iran (Islamic Republic of)' },
      { id: 68, nom: 'Iraq' },
      { id: 69, nom: 'Ireland' },
      { id: 70, nom: 'Israel' },
      { id: 71, nom: 'Italy' },
      { id: 72, nom: 'Jamaica' },
      { id: 73, nom: 'Japan' },
      { id: 74, nom: 'Jordan' },
      { id: 75, nom: 'Kazakhstan' },
      { id: 76, nom: 'Kenya' },
      { id: 77, nom: 'Kiribati' },
      { id: 78, nom: "Lao People's Democratic Republic" },
      { id: 79, nom: 'Latvia' },
      { id: 80, nom: 'Lebanon' },
      { id: 81, nom: 'Lesotho' },
      { id: 82, nom: 'Libya' },
      { id: 83, nom: 'Lithuania' },
      { id: 84, nom: 'Luxembourg' },
      { id: 85, nom: 'Madagascar' },
      { id: 86, nom: 'Malawi' },
      { id: 87, nom: 'Malaysia' },
      { id: 88, nom: 'Mali' },
      { id: 89, nom: 'Malta' },
      { id: 90, nom: 'Marshall Islands' },
      { id: 91, nom: 'Mauritania' },
      { id: 92, nom: 'Mauritius' },
      { id: 93, nom: 'Mexico' },
      { id: 94, nom: 'Micronesia (Federated States of)' },
      { id: 95, nom: 'Moldova (Republic of)' },
      { id: 96, nom: 'Mongolia' },
      { id: 97, nom: 'Montenegro' },
      { id: 98, nom: 'Morocco' },
      { id: 99, nom: 'Mozambique' },
      { id: 100, nom: 'Myanmar' },
      { id: 101, nom: 'Namibia' },
      { id: 102, nom: 'Nepal' },
      { id: 103, nom: 'Netherlands' },
      { id: 104, nom: 'New Zealand' },
      { id: 105, nom: 'Nicaragua' },
      { id: 106, nom: 'Niger' },
      { id: 107, nom: 'Nigeria' },
      { id: 108, nom: 'Norway' },
      { id: 109, nom: 'Oman' },
      { id: 110, nom: 'Pakistan' },
      { id: 111, nom: 'Palau' },
      { id: 112, nom: 'Palestine' },
      { id: 113, nom: 'Panama' },
      { id: 114, nom: 'Papua New Guinea' },
      { id: 115, nom: 'Paraguay' },
      { id: 116, nom: 'Peru' },
      { id: 117, nom: 'Philippines' },
      { id: 118, nom: 'Poland' },
      { id: 119, nom: 'Portugal' },
      { id: 120, nom: 'Qatar' },
      { id: 121, nom: 'Republic of Korea' },
      { id: 122, nom: 'Romania' },
      { id: 123, nom: 'Russian Federation' },
      { id: 124, nom: 'Saint Kitts and Nevis' },
      { id: 125, nom: 'Saint Lucia' },
      { id: 126, nom: 'Saudi Arabia' },
      { id: 127, nom: 'Senegal' },
      { id: 128, nom: 'Serbia' },
      { id: 129, nom: 'Seychelles' },
      { id: 130, nom: 'Singapore' },
      { id: 131, nom: 'Slovakia' },
      { id: 132, nom: 'Slovenia' },
      { id: 133, nom: 'Solomon Islands' },
      { id: 134, nom: 'South Africa' },
      { id: 135, nom: 'Spain' },
      { id: 136, nom: 'Sri Lanka' },
      { id: 137, nom: 'Sudan' },
      { id: 138, nom: 'Surinom' },
      { id: 139, nom: 'Sweden' },
      { id: 140, nom: 'Switzerland' },
      { id: 141, nom: 'Syrian Arab Republic' },
      { id: 142, nom: 'Tajikistan' },
      { id: 143, nom: 'Thailand' },
      { id: 144, nom: 'Tunisia' },
      { id: 145, nom: 'Turkey' },
      { id: 146, nom: 'Uganda' },
      { id: 147, nom: 'Ukraine' },
      { id: 148, nom: 'United Arab Emirates' },
      { id: 149, nom: 'United Kingdom of Great Britain and Northern Ireland' },
      { id: 150, nom: 'United Republic of Tanzania' },
      { id: 151, nom: 'United States of America' },
      { id: 152, nom: 'Uruguay' },
      { id: 153, nom: 'Uzbekistan' },
      { id: 154, nom: 'Vanuatu' },
      { id: 155, nom: 'Venezuela (Bolivarian Republic of)' },
      { id: 156, nom: 'Viet Nam' },
      { id: 157, nom: 'Yemen' },
      { id: 158, nom: 'Zambia' },
      { id: 159, nom: 'Zimbabwe' },
    ])
  }
}
