/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  NewAccount: () => import('#controllers/new_account_controller'),
  Pays: () => import('#controllers/pays_controller'),
  Regions: () => import('#controllers/regions_controller'),
  Session: () => import('#controllers/session_controller'),
  Sites: () => import('#controllers/sites_controller'),
  Stats: () => import('#controllers/stats_controller'),
  VisitedSites: () => import('#controllers/visited_sites_controller'),
}
